
package com.amazonaws.fps.model;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransactionId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OverrideIPNURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Mon May 30 08:10:15 GMT+00:00 2011
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transactionId",
    "description",
    "overrideIPNURL"
})
@XmlRootElement(name = "CancelRequest")
public class CancelRequest {

    @XmlElement(name = "TransactionId")
    protected String transactionId;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "OverrideIPNURL")
    protected String overrideIPNURL;

    /**
     * Default constructor
     * 
     */
    public CancelRequest() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public CancelRequest(final String transactionId, final String description, final String overrideIPNURL) {
        this.transactionId = transactionId;
        this.description = description;
        this.overrideIPNURL = overrideIPNURL;
    }

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

    public boolean isSetTransactionId() {
        return (this.transactionId!= null);
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    public boolean isSetDescription() {
        return (this.description!= null);
    }

    /**
     * Gets the value of the overrideIPNURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOverrideIPNURL() {
        return overrideIPNURL;
    }

    /**
     * Sets the value of the overrideIPNURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOverrideIPNURL(String value) {
        this.overrideIPNURL = value;
    }

    public boolean isSetOverrideIPNURL() {
        return (this.overrideIPNURL!= null);
    }

    /**
     * Sets the value of the TransactionId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public CancelRequest withTransactionId(String value) {
        setTransactionId(value);
        return this;
    }

    /**
     * Sets the value of the Description property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public CancelRequest withDescription(String value) {
        setDescription(value);
        return this;
    }

    /**
     * Sets the value of the OverrideIPNURL property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public CancelRequest withOverrideIPNURL(String value) {
        setOverrideIPNURL(value);
        return this;
    }
    


    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetTransactionId()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("TransactionId"));
            json.append(" : ");
            json.append(quoteJSON(getTransactionId()));
            first = false;
        }
        if (isSetDescription()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("Description"));
            json.append(" : ");
            json.append(quoteJSON(getDescription()));
            first = false;
        }
        if (isSetOverrideIPNURL()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("OverrideIPNURL"));
            json.append(" : ");
            json.append(quoteJSON(getOverrideIPNURL()));
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
