
package com.amazonaws.fps.model;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SubscriptionTransaction" type="{http://fps.amazonaws.com/doc/2010-08-28/}SubscriptionTransaction" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Mon May 30 08:10:15 GMT+00:00 2011
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "subscriptionTransaction"
})
@XmlRootElement(name = "GetTransactionsForSubscriptionResult")
public class GetTransactionsForSubscriptionResult {

    @XmlElement(name = "SubscriptionTransaction")
    protected List<SubscriptionTransaction> subscriptionTransaction;

    /**
     * Default constructor
     * 
     */
    public GetTransactionsForSubscriptionResult() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public GetTransactionsForSubscriptionResult(final List<SubscriptionTransaction> subscriptionTransaction) {
        this.subscriptionTransaction = subscriptionTransaction;
    }

    /**
     * Gets the value of the subscriptionTransaction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subscriptionTransaction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubscriptionTransaction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubscriptionTransaction }
     *
     *
     */
    public List<SubscriptionTransaction> getSubscriptionTransaction() {
        if (subscriptionTransaction == null) {
            subscriptionTransaction = new ArrayList<SubscriptionTransaction>();
        }
        return this.subscriptionTransaction;
    }

    public boolean isSetSubscriptionTransaction() {
        return ((this.subscriptionTransaction!= null)&&(!this.subscriptionTransaction.isEmpty()));
    }

    public void unsetSubscriptionTransaction() {
        this.subscriptionTransaction = null;
    }

    /**
     * Sets the value of the SubscriptionTransaction property.
     *
     * @param values
     * @return
     *     this instance
     */
    public GetTransactionsForSubscriptionResult withSubscriptionTransaction(SubscriptionTransaction... values) {
        for (SubscriptionTransaction value: values) {
            getSubscriptionTransaction().add(value);
        }
        return this;
    }

    /**
     * Sets the value of the subscriptionTransaction property.
     *
     * @param subscriptionTransaction
     *     allowed object is
     *     {@link SubscriptionTransaction }
     *
     */
    public void setSubscriptionTransaction(List<SubscriptionTransaction> subscriptionTransaction) {
        this.subscriptionTransaction = subscriptionTransaction;
    }


    /**
     *
     * XML fragment representation of this object
     *
     * @return XML fragment for this object. Name for outer
     * tag expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toXMLFragment() {
        StringBuffer xml = new StringBuffer();
        List<SubscriptionTransaction> subscriptionTransactionList = getSubscriptionTransaction();
        for (SubscriptionTransaction subscriptionTransaction : subscriptionTransactionList) {
            xml.append("<SubscriptionTransaction>");
            xml.append(subscriptionTransaction.toXMLFragment());
            xml.append("</SubscriptionTransaction>");
        }
        return xml.toString();
    }

    /**
     *
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }



    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetSubscriptionTransaction()) {
            if (!first) json.append(", ");
            json.append("\"SubscriptionTransaction\" : [");
            List<SubscriptionTransaction> subscriptionTransactionList = getSubscriptionTransaction();
            int subscriptionTransactionListIndex = 0;
            for (SubscriptionTransaction subscriptionTransaction : subscriptionTransactionList) {
                if (subscriptionTransactionListIndex > 0) json.append(", ");
                json.append("{");
                json.append("");
                json.append(subscriptionTransaction.toJSONFragment());
                json.append("}");
                first = false;
                ++subscriptionTransactionListIndex;
            }
            json.append("]");
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
