/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2014-08-07 09:11:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    /* *
     *功能：支付宝即时到账交易接口调试入口页面
     *版本：3.3
     *日期：2012-08-17
     *说明：
     *以下代码只是为了方便商户测试而提供的样例代码，商户可以根据自己网站的需要，按照技术文档编写,并非一定要使用该代码。
     */

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>支付接口测试_用户登录</title>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ul, ol {\r\n");
      out.write("            list-style: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .title {\r\n");
      out.write("            color: #ADADAD;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            padding: 8px 16px 5px 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hidden {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .new-btn-login-sp {\r\n");
      out.write("            border: 1px solid #D74C00;\r\n");
      out.write("            padding: 1px;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .new-btn-login {\r\n");
      out.write("            background-color: transparent;\r\n");
      out.write("            background-image: url(\"../images/new-btn-fixed.png\");\r\n");
      out.write("            border: medium none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .new-btn-login {\r\n");
      out.write("            background-position: 0 -198px;\r\n");
      out.write("            width: 82px;\r\n");
      out.write("            color: #FFFFFF;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            height: 28px;\r\n");
      out.write("            line-height: 28px;\r\n");
      out.write("            padding: 0 10px 3px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .new-btn-login:hover {\r\n");
      out.write("            background-position: 0 -167px;\r\n");
      out.write("            width: 82px;\r\n");
      out.write("            color: #FFFFFF;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            height: 28px;\r\n");
      out.write("            line-height: 28px;\r\n");
      out.write("            padding: 0 10px 3px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bank-list {\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            margin-top: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bank-list li {\r\n");
      out.write("            float: left;\r\n");
      out.write("            width: 153px;\r\n");
      out.write("            margin-bottom: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #main {\r\n");
      out.write("            width: 750px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            font-family: '宋体';\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #logo {\r\n");
      out.write("            background-color: transparent;\r\n");
      out.write("            background-image: url(\"../images/new-btn-fixed.png\");\r\n");
      out.write("            border: medium none;\r\n");
      out.write("            background-position: 0 0;\r\n");
      out.write("            width: 166px;\r\n");
      out.write("            height: 35px;\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .red-star {\r\n");
      out.write("            color: #f00;\r\n");
      out.write("            width: 10px;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .null-star {\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .content {\r\n");
      out.write("            margin-top: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .content dt {\r\n");
      out.write("            width: 160px;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            text-align: right;\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .content dd {\r\n");
      out.write("            margin-left: 100px;\r\n");
      out.write("            margin-bottom: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #foot {\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .foot-ul li {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .note-help {\r\n");
      out.write("            color: #999999;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            line-height: 130%;\r\n");
      out.write("            padding-left: 3px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cashier-nav {\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            margin: 15px 0 10px;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            border-bottom: solid 2px #CFD2D7;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cashier-nav ol li {\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cashier-nav li.current {\r\n");
      out.write("            color: #AB4400;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cashier-nav li.last {\r\n");
      out.write("            clear: right;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .alipay_link {\r\n");
      out.write("            text-align: right;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .alipay_link a:link {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: #8D8D8D;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .alipay_link a:visited {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: #8D8D8D;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        function changeImg(el){\r\n");
      out.write("//            alert((Math.random()*1000+\"\").substr(0,3));\r\n");
      out.write("//            el.src=\"RandImg.jpg?time=\"+(Math.random()*1000+\"\").substr(0,3);\r\n");
      out.write("            el.src=\"RandImg.jpg?time=\"+new Date().getTime();\r\n");
      out.write("//            alert(el.src);\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body text=#000000 bgColor=\"#ffffff\" leftMargin=0 topMargin=4>\r\n");
      out.write("<div id=\"main\">\r\n");
      out.write("    <div id=\"head\">\r\n");
      out.write("        <dl class=\"alipay_link\">\r\n");
      out.write("            <a target=\"_blank\" href=\"www.paypal.com/\"><span>Paypal首页</span></a>|\r\n");
      out.write("            <a target=\"_blank\" href=\"https://www.paypal.com/hk/webapps/mpp/merchant?locale.x=zh_HK\"><span>商家服务</span></a>|\r\n");
      out.write("            <a target=\"_blank\" href=\"https://www.paypal.com/cn/webapps/helpcenter/home/\"><span>帮助中心</span></a>\r\n");
      out.write("        </dl>\r\n");
      out.write("        <span class=\"title\">用户登录</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"cashier-nav\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("       <form name=alipayment action=/jsp/login.jsp method=post >\r\n");
      out.write("        <div id=\"body\" style=\"clear:left\">\r\n");
      out.write("            <dl class=\"content\">\r\n");
      out.write("                <dt>用户名：</dt>\r\n");
      out.write("                <dd>\r\n");
      out.write("                    <span class=\"null-star\">*</span>\r\n");
      out.write("                    <input type=\"text\" size=\"30\" name=\"username\"/>\r\n");
      out.write("\t\t\t\t\t\t<span>必填\r\n");
      out.write("</span>\r\n");
      out.write("                </dd>\r\n");
      out.write("                <dt>用户密码</dt>\r\n");
      out.write("                <dd>\r\n");
      out.write("                    <span class=\"null-star\">*</span>\r\n");
      out.write("                    <input type=\"password\" size=\"30\" name=\"password\"/>\r\n");
      out.write("\t\t\t\t\t\t<span>密码为6-16位字母或数字\r\n");
      out.write("</span>\r\n");
      out.write("                </dd>\r\n");
      out.write("                <dt></dt>\r\n");
      out.write("                <dd>\r\n");
      out.write("                        <span class=\"new-btn-login-sp\">\r\n");
      out.write("                            <button class=\"new-btn-login\" type=\"submit\" style=\"text-align:center;\">登录</button>\r\n");
      out.write("                        </span>\r\n");
      out.write("                </dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("        </div>\r\n");
      out.write("           <img src=\"/RandImg.jpg\" alt=\"验证码\" onclick=\"changeImg(this)\"/><input type=\"text\" name=\"RandImg\" value=\"\" onblur=\"alert(this.value);\"/>\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent(null);
    // /jsp/index.jsp(226,4) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.imageCode}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }
}
