package com.qpp.model;

// Generated Sep 24, 2014 2:42:53 PM by Hibernate Tools 3.4.0.CR1

/**
 * TAvailableApp generated by hbm2java
 */
public class TAvailableApp implements java.io.Serializable {

	private long oid;
	private long userId;
	private long appId;

	public TAvailableApp() {
	}

	public TAvailableApp(long userId, long appId) {
		this.userId = userId;
		this.appId = appId;
	}

	public long getOid() {
		return this.oid;
	}

	public void setOid(long oid) {
		this.oid = oid;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public long getAppId() {
		return this.appId;
	}

	public void setAppId(long appId) {
		this.appId = appId;
	}

}
