package com.qpp.model;

// Generated Aug 28, 2014 4:18:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TCartItem generated by hbm2java
 */
public class TCartItem implements java.io.Serializable {

	private int id;
	private TUser userId;
	private int productId;
	private String productSpec;
	private int productCount;
	private Date ctime;
	private String comment;
	private double price;
	private String imgUrl;
	private String url;
	private String productName;

	public TCartItem() {
	}

	public TCartItem(int productCount, Date ctime, double price) {
		this.productCount = productCount;
		this.ctime = ctime;
		this.price = price;
	}

	public TCartItem(TUser userId, int productId, String productSpec,
			int productCount, Date ctime, String comment, double price,
			String imgUrl, String url, String productName) {
		this.userId=userId;
		this.productId = productId;
		this.productSpec = productSpec;
		this.productCount = productCount;
		this.ctime = ctime;
		this.comment = comment;
		this.price = price;
		this.imgUrl = imgUrl;
		this.url = url;
		this.productName = productName;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

    public TUser getUserId() {
        return userId;
    }

    public void setUserId(TUser userId) {
        this.userId = userId;
    }

    public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public String getProductSpec() {
		return this.productSpec;
	}

	public void setProductSpec(String productSpec) {
		this.productSpec = productSpec;
	}

	public int getProductCount() {
		return this.productCount;
	}

	public void setProductCount(int productCount) {
		this.productCount = productCount;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public String getImgUrl() {
		return this.imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

}
