package com.qpp.model;

// Generated Aug 6, 2014 1:48:13 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TCartItem generated by hbm2java
 */
public class TCartItem implements java.io.Serializable {

	private String id;
	private String userId;
	private String productId;
	private String productSpec;
	private int productCount;
	private Date ctime;
	private String comment;
	private double price;
	private String imgUrl;
	private String url;

	public TCartItem() {
	}

	public TCartItem(String id, String userId, String productId,
			String productSpec, int productCount, Date ctime, String comment,
			double price, String imgUrl, String url) {
		this.id = id;
		this.userId = userId;
		this.productId = productId;
		this.productSpec = productSpec;
		this.productCount = productCount;
		this.ctime = ctime;
		this.comment = comment;
		this.price = price;
		this.imgUrl = imgUrl;
		this.url = url;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getProductSpec() {
		return this.productSpec;
	}

	public void setProductSpec(String productSpec) {
		this.productSpec = productSpec;
	}

	public int getProductCount() {
		return this.productCount;
	}

	public void setProductCount(int productCount) {
		this.productCount = productCount;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public String getImgUrl() {
		return this.imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
