package com.qpp.model;

// Generated Sep 24, 2014 2:42:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TConvert generated by hbm2java
 */
public class TConvert implements java.io.Serializable {

	private long id;
	private String type;
	private int amount;
	private Date ctime;
	private long userId;
	private String comment;
	private long giftId;
	private int count;

	public TConvert() {
	}

	public TConvert(int amount, Date ctime, int count) {
		this.amount = amount;
		this.ctime = ctime;
		this.count = count;
	}

	public TConvert(String type, int amount, Date ctime, long userId,
			String comment, long giftId, int count) {
		this.type = type;
		this.amount = amount;
		this.ctime = ctime;
		this.userId = userId;
		this.comment = comment;
		this.giftId = giftId;
		this.count = count;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}
	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

    public long getGiftId() {
        return giftId;
    }

    public void setGiftId(long giftId) {
        this.giftId = giftId;
    }
}
