package com.qpp.model;

// Generated Aug 28, 2014 4:18:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TConvert generated by hbm2java
 */
public class TConvert implements java.io.Serializable {

	private int id;
	private TGift target;
	private TUser userId;
	private String type;
	private int amount;
	private Date ctime;
	private String comment;
	private int count;

	public TConvert() {
	}

	public TConvert(int amount, Date ctime, int count) {
		this.amount = amount;
		this.ctime = ctime;
		this.count = count;
	}

	public TConvert(TGift TGift, TUser userId, String type, int amount,
			Date ctime, String comment, int count) {
        this.userId=userId;
        this.target=target;
		this.type = type;
		this.amount = amount;
		this.ctime = ctime;
		this.comment = comment;
		this.count = count;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

    public TGift getTarget() {
        return target;
    }

    public void setTarget(TGift target) {
        this.target = target;
    }

    public TUser getUserId() {
        return userId;
    }

    public void setUserId(TUser userId) {
        this.userId = userId;
    }

    public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

}
