package com.qpp.model;

// Generated Aug 6, 2014 1:48:13 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TConvert generated by hbm2java
 */
public class TConvert implements java.io.Serializable {

	private String id;
	private String type;
	private int amount;
	private Date ctime;
	private String userId;
	private String comment;
	private String target;

	public TConvert() {
	}

	public TConvert(String id, String type, int amount, Date ctime,
			String userId, String comment, String target) {
		this.id = id;
		this.type = type;
		this.amount = amount;
		this.ctime = ctime;
		this.userId = userId;
		this.comment = comment;
		this.target = target;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

}
