package com.qpp.model;

// Generated Aug 22, 2014 1:22:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TFavorite generated by hbm2java
 */
public class TFavorite implements java.io.Serializable {

	private String userId;
	private TUser TUser;
	private String type;
	private String productName;
	private String productId;
	private String comment;
	private Date ctime;

	public TFavorite() {
	}

	public TFavorite(TUser TUser, String type, String productName,
			String productId, String comment, Date ctime) {
		this.TUser = TUser;
		this.type = type;
		this.productName = productName;
		this.productId = productId;
		this.comment = comment;
		this.ctime = ctime;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

}
