package com.qpp.model;

// Generated Sep 24, 2014 2:42:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TFavorite generated by hbm2java
 */
public class TFavorite implements java.io.Serializable {

	private long userId;
	private String type;
	private String productName;
	private long productId;
	private String comment;
	private Date ctime;

	public TFavorite() {
	}

	public TFavorite(Date ctime) {
		this.ctime = ctime;
	}

	public TFavorite(String type, String productName, long productId,
			String comment, Date ctime) {
		this.type = type;
		this.productName = productName;
		this.productId = productId;
		this.comment = comment;
		this.ctime = ctime;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public long getProductId() {
		return this.productId;
	}

	public void setProductId(long productId) {
		this.productId = productId;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

}
