package com.qpp.model;

// Generated Aug 12, 2014 11:53:34 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TGift generated by hbm2java
 */
public class TGift implements java.io.Serializable {

	private String id;
	private String name;
	private String type;
	private int price;
	private int priceTwo;
	private int count;
	private Date ctime;
	private Set<TScore> TScores = new HashSet<TScore>(0);
	private Set<TUser> TUsers = new HashSet<TUser>(0);
	private Set<TConvert> TConverts = new HashSet<TConvert>(0);

	public TGift() {
	}

	public TGift(String id, String name, String type, int price, int priceTwo,
			int count, Date ctime) {
		this.id = id;
		this.name = name;
		this.type = type;
		this.price = price;
		this.priceTwo = priceTwo;
		this.count = count;
		this.ctime = ctime;
	}

	public TGift(String id, String name, String type, int price, int priceTwo,
			int count, Date ctime, Set<TScore> TScores, Set<TUser> TUsers,
			Set<TConvert> TConverts) {
		this.id = id;
		this.name = name;
		this.type = type;
		this.price = price;
		this.priceTwo = priceTwo;
		this.count = count;
		this.ctime = ctime;
		this.TScores = TScores;
		this.TUsers = TUsers;
		this.TConverts = TConverts;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public int getPriceTwo() {
		return this.priceTwo;
	}

	public void setPriceTwo(int priceTwo) {
		this.priceTwo = priceTwo;
	}

	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public Set<TScore> getTScores() {
		return this.TScores;
	}

	public void setTScores(Set<TScore> TScores) {
		this.TScores = TScores;
	}

	public Set<TUser> getTUsers() {
		return this.TUsers;
	}

	public void setTUsers(Set<TUser> TUsers) {
		this.TUsers = TUsers;
	}

	public Set<TConvert> getTConverts() {
		return this.TConverts;
	}

	public void setTConverts(Set<TConvert> TConverts) {
		this.TConverts = TConverts;
	}

}
