package com.qpp.model;

// Generated Sep 24, 2014 2:42:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TGift generated by hbm2java
 */
public class TGift implements java.io.Serializable {

	private long id;
	private String name;
	private String type;
	private int price;
	private double priceTwo;
	private Integer count;
	private Date ctime;

	public TGift() {
	}

	public TGift(String name, int price, Date ctime) {
		this.name = name;
		this.price = price;
		this.ctime = ctime;
	}

	public TGift(String name, String type, int price, Integer priceTwo,
			Integer count, Date ctime) {
		this.name = name;
		this.type = type;
		this.price = price;
		this.priceTwo = priceTwo;
		this.count = count;
		this.ctime = ctime;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public double getPriceTwo() {
		return this.priceTwo;
	}

	public void setPriceTwo(double priceTwo) {
		this.priceTwo = priceTwo;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

}
