package com.qpp.model;

// Generated Sep 24, 2014 2:42:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TMailPublish generated by hbm2java
 */
public class TMailPublish implements java.io.Serializable {

	private long id;
	private String subject;
	private String fromm;
	private String attachment;
	private String cc;
	private String content;
	private Date sendDate;
	private Date ctime;
	private String comment;
	private String isPublish;

	public TMailPublish() {
	}

	public TMailPublish(String subject, String content, Date sendDate,
			Date ctime, String isPublish) {
		this.subject = subject;
		this.content = content;
		this.sendDate = sendDate;
		this.ctime = ctime;
		this.isPublish = isPublish;
	}

	public TMailPublish(String subject, String fromm, String attachment,
			String cc, String content, Date sendDate, Date ctime,
			String comment, String isPublish) {
		this.subject = subject;
		this.fromm = fromm;
		this.attachment = attachment;
		this.cc = cc;
		this.content = content;
		this.sendDate = sendDate;
		this.ctime = ctime;
		this.comment = comment;
		this.isPublish = isPublish;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getFromm() {
		return this.fromm;
	}

	public void setFromm(String fromm) {
		this.fromm = fromm;
	}

	public String getAttachment() {
		return this.attachment;
	}

	public void setAttachment(String attachment) {
		this.attachment = attachment;
	}

	public String getCc() {
		return this.cc;
	}

	public void setCc(String cc) {
		this.cc = cc;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getSendDate() {
		return this.sendDate;
	}

	public void setSendDate(Date sendDate) {
		this.sendDate = sendDate;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getIsPublish() {
		return this.isPublish;
	}

	public void setIsPublish(String isPublish) {
		this.isPublish = isPublish;
	}

}
