package com.qpp.model;

// Generated Sep 24, 2014 2:42:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TOrderItem generated by hbm2java
 */
public class TOrderItem implements java.io.Serializable {

	private long id;
	private long orderId;
	private long productId;
	private String productName;
	private long productCount;
	private String productSpec;
	private String comment;
	private Date ctime;
	private Date utime;
	private String isbn;
	private Double price;

	public TOrderItem() {
	}

	public TOrderItem(long orderId, long productId, String productName,
			long productCount, String productSpec, String comment,
			Date ctime, Date utime, String isbn, Double price) {
		this.orderId = orderId;
		this.productId = productId;
		this.productName = productName;
		this.productCount = productCount;
		this.productSpec = productSpec;
		this.comment = comment;
		this.ctime = ctime;
		this.utime = utime;
		this.isbn = isbn;
		this.price = price;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	public long getProductId() {
		return this.productId;
	}

	public void setProductId(long productId) {
		this.productId = productId;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public long getProductCount() {
		return this.productCount;
	}

	public void setProductCount(long productCount) {
		this.productCount = productCount;
	}

	public String getProductSpec() {
		return this.productSpec;
	}

	public void setProductSpec(String productSpec) {
		this.productSpec = productSpec;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public Date getUtime() {
		return this.utime;
	}

	public void setUtime(Date utime) {
		this.utime = utime;
	}

	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

}
