package com.qpp.model;

// Generated Aug 6, 2014 1:48:13 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TOrderItem generated by hbm2java
 */
public class TOrderItem implements java.io.Serializable {

	private String id;
	private TOrder TOrder;
	private String productId;
	private String productName;
	private Integer productCount;
	private String productSpec;
	private String comment;
	private Date ctime;
	private Date utime;
	private String isbn;
	private Double price;

	public TOrderItem() {
	}

	public TOrderItem(String id, String productId) {
		this.id = id;
		this.productId = productId;
	}

	public TOrderItem(String id, TOrder TOrder, String productId,
			String productName, Integer productCount, String productSpec,
			String comment, Date ctime, Date utime, String isbn, Double price) {
		this.id = id;
		this.TOrder = TOrder;
		this.productId = productId;
		this.productName = productName;
		this.productCount = productCount;
		this.productSpec = productSpec;
		this.comment = comment;
		this.ctime = ctime;
		this.utime = utime;
		this.isbn = isbn;
		this.price = price;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public TOrder getTOrder() {
		return this.TOrder;
	}

	public void setTOrder(TOrder TOrder) {
		this.TOrder = TOrder;
	}

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public Integer getProductCount() {
		return this.productCount;
	}

	public void setProductCount(Integer productCount) {
		this.productCount = productCount;
	}

	public String getProductSpec() {
		return this.productSpec;
	}

	public void setProductSpec(String productSpec) {
		this.productSpec = productSpec;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public Date getUtime() {
		return this.utime;
	}

	public void setUtime(Date utime) {
		this.utime = utime;
	}

	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

}
