package com.qpp.model;

// Generated Aug 22, 2014 1:22:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TOrder generated by hbm2java
 */
public class TOrder implements java.io.Serializable {

	private String id;
	private TUser TUser;
	private Double amt;
	private String currencyCode;
	private Double maxAmt;
	private String payMentAction;
	private String email;
	private String address;
	private String phone;
	private String zipCode;
	private String desc;
	private String invnum;
	private String transactionId;
	private String localCode;
	private Date ctime;
	private Date utime;
	private String status;
	private Double itemAmt;
	private Double taxAmt;
	private Double shippingAmt;
	private Double insuranceAmt;
	private String shippingType;
	private Double shippingNum;
	private String type;
	private Set<TOrderItem> TOrderItems = new HashSet<TOrderItem>(0);

	public TOrder() {
	}

	public TOrder(String id, String type) {
		this.id = id;
		this.type = type;
	}

	public TOrder(String id, TUser TUser, Double amt, String currencyCode,
			Double maxAmt, String payMentAction, String email, String address,
			String phone, String zipCode, String desc, String invnum,
			String transactionId, String localCode, Date ctime, Date utime,
			String status, Double itemAmt, Double taxAmt, Double shippingAmt,
			Double insuranceAmt, String shippingType, Double shippingNum,
			String type, Set<TOrderItem> TOrderItems) {
		this.id = id;
		this.TUser = TUser;
		this.amt = amt;
		this.currencyCode = currencyCode;
		this.maxAmt = maxAmt;
		this.payMentAction = payMentAction;
		this.email = email;
		this.address = address;
		this.phone = phone;
		this.zipCode = zipCode;
		this.desc = desc;
		this.invnum = invnum;
		this.transactionId = transactionId;
		this.localCode = localCode;
		this.ctime = ctime;
		this.utime = utime;
		this.status = status;
		this.itemAmt = itemAmt;
		this.taxAmt = taxAmt;
		this.shippingAmt = shippingAmt;
		this.insuranceAmt = insuranceAmt;
		this.shippingType = shippingType;
		this.shippingNum = shippingNum;
		this.type = type;
		this.TOrderItems = TOrderItems;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	public Double getAmt() {
		return this.amt;
	}

	public void setAmt(Double amt) {
		this.amt = amt;
	}

	public String getCurrencyCode() {
		return this.currencyCode;
	}

	public void setCurrencyCode(String currencyCode) {
		this.currencyCode = currencyCode;
	}

	public Double getMaxAmt() {
		return this.maxAmt;
	}

	public void setMaxAmt(Double maxAmt) {
		this.maxAmt = maxAmt;
	}

	public String getPayMentAction() {
		return this.payMentAction;
	}

	public void setPayMentAction(String payMentAction) {
		this.payMentAction = payMentAction;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	public String getInvnum() {
		return this.invnum;
	}

	public void setInvnum(String invnum) {
		this.invnum = invnum;
	}

	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public String getLocalCode() {
		return this.localCode;
	}

	public void setLocalCode(String localCode) {
		this.localCode = localCode;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public Date getUtime() {
		return this.utime;
	}

	public void setUtime(Date utime) {
		this.utime = utime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Double getItemAmt() {
		return this.itemAmt;
	}

	public void setItemAmt(Double itemAmt) {
		this.itemAmt = itemAmt;
	}

	public Double getTaxAmt() {
		return this.taxAmt;
	}

	public void setTaxAmt(Double taxAmt) {
		this.taxAmt = taxAmt;
	}

	public Double getShippingAmt() {
		return this.shippingAmt;
	}

	public void setShippingAmt(Double shippingAmt) {
		this.shippingAmt = shippingAmt;
	}

	public Double getInsuranceAmt() {
		return this.insuranceAmt;
	}

	public void setInsuranceAmt(Double insuranceAmt) {
		this.insuranceAmt = insuranceAmt;
	}

	public String getShippingType() {
		return this.shippingType;
	}

	public void setShippingType(String shippingType) {
		this.shippingType = shippingType;
	}

	public Double getShippingNum() {
		return this.shippingNum;
	}

	public void setShippingNum(Double shippingNum) {
		this.shippingNum = shippingNum;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set<TOrderItem> getTOrderItems() {
		return this.TOrderItems;
	}

	public void setTOrderItems(Set<TOrderItem> TOrderItems) {
		this.TOrderItems = TOrderItems;
	}

}
