package com.qpp.model;

// Generated Aug 28, 2014 4:18:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TOrderItem generated by hbm2java
 */
public class TOrderItem implements java.io.Serializable {

        private int id;
	private TOrder orderId;
	private int productId;
	private String productName;
	private int productCount;
	private String productSpec;
	private String comment;
	private Date ctime;
	private Date utime;
	private String isbn;
	private Double price;

	public TOrderItem() {
	}

	public TOrderItem(TOrder orderId, int productId, String productName,
			int productCount, String productSpec, String comment,
			Date ctime, Date utime, String isbn, Double price) {
        this.orderId=orderId;
		this.productId = productId;
		this.productName = productName;
		this.productCount = productCount;
		this.productSpec = productSpec;
		this.comment = comment;
		this.ctime = ctime;
		this.utime = utime;
		this.isbn = isbn;
		this.price = price;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

    public TOrder getOrderId() {
        return orderId;
    }

    public void setOrderId(TOrder orderId) {
        this.orderId = orderId;
    }

    public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public int getProductCount() {
		return this.productCount;
	}

	public void setProductCount(int productCount) {
		this.productCount = productCount;
	}

	public String getProductSpec() {
		return this.productSpec;
	}

	public void setProductSpec(String productSpec) {
		this.productSpec = productSpec;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public Date getUtime() {
		return this.utime;
	}

	public void setUtime(Date utime) {
		this.utime = utime;
	}

	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

}
