package com.qpp.model;

// Generated Sep 29, 2014 2:40:36 PM by Hibernate Tools 3.4.0.CR1

import javax.validation.constraints.NotNull;

/**
 * TRole generated by hbm2java
 */
public class TRole extends Priciple implements java.io.Serializable {

	private String roleName;
	private String roleDesc;
    @NotNull
	private long appId;

	public TRole() {
	}

	public TRole(String roleName, String roleDesc, int appId) {
		this.roleName = roleName;
		this.roleDesc = roleDesc;
		this.appId = appId;
	}

	public long getOid() {
		return this.oid;
	}

	public void setOid(long oid) {
		this.oid = oid;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getRoleDesc() {
		return this.roleDesc;
	}

	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

	public long getAppId() {
		return this.appId;
	}

	public void setAppId(long appId) {
		this.appId = appId;
	}

}
