package com.qpp.model;

// Generated Aug 22, 2014 1:22:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TScore generated by hbm2java
 */
public class TScore implements java.io.Serializable {

	private String id;
	private Date ctime;
	private String type;
	private int size;
	private String userId;
	private Integer count;
	private String status;
	private String comment;

	public TScore() {
	}

	public TScore(String id, Date ctime, int size, String status, String comment) {
		this.id = id;
		this.ctime = ctime;
		this.size = size;
		this.status = status;
		this.comment = comment;
	}

	public TScore(String id, Date ctime, String type, int size, String userId,
			Integer count, String status, String comment) {
		this.id = id;
		this.ctime = ctime;
		this.type = type;
		this.size = size;
		this.userId = userId;
		this.count = count;
		this.status = status;
		this.comment = comment;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public int getSize() {
		return this.size;
	}

	public void setSize(int size) {
		this.size = size;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
