package com.qpp.model;

// Generated Sep 24, 2014 2:42:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TScore generated by hbm2java
 */
public class TScore implements java.io.Serializable {

	private long id;
	private Date ctime;
	private String type;
	private int size;
	private long userId;
	private long count;
	private String status;
	private String comment;

	public TScore() {
	}

	public TScore(Date ctime, int size, String status, String comment) {
		this.ctime = ctime;
		this.size = size;
		this.status = status;
		this.comment = comment;
	}

	public TScore(Date ctime, String type, int size, long userId,
			long count, String status, String comment) {
		this.ctime = ctime;
		this.type = type;
		this.size = size;
		this.userId = userId;
		this.count = count;
		this.status = status;
		this.comment = comment;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public int getSize() {
		return this.size;
	}

	public void setSize(int size) {
		this.size = size;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public long getCount() {
		return this.count;
	}

	public void setCount(long count) {
		this.count = count;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
