package com.qpp.model;

// Generated Aug 6, 2014 1:48:13 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TScore generated by hbm2java
 */
public class TScore implements java.io.Serializable {

	private String id;
	private TGift TGift;
	private TUser TUser;
	private Date ctime;
	private int size;
	private Integer count;
	private String status;
	private String comment;

	public TScore() {
	}

	public TScore(String id, TUser TUser, Date ctime, int size, String status,
			String comment) {
		this.id = id;
		this.TUser = TUser;
		this.ctime = ctime;
		this.size = size;
		this.status = status;
		this.comment = comment;
	}

	public TScore(String id, TGift TGift, TUser TUser, Date ctime, int size,
			Integer count, String status, String comment) {
		this.id = id;
		this.TGift = TGift;
		this.TUser = TUser;
		this.ctime = ctime;
		this.size = size;
		this.count = count;
		this.status = status;
		this.comment = comment;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public TGift getTGift() {
		return this.TGift;
	}

	public void setTGift(TGift TGift) {
		this.TGift = TGift;
	}

	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public int getSize() {
		return this.size;
	}

	public void setSize(int size) {
		this.size = size;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
