package com.qpp.model;

// Generated Aug 22, 2014 1:22:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TStateInfo generated by hbm2java
 */
public class TStateInfo implements java.io.Serializable {

	private String stateCode;
	private String currencyCode;
	private String cardInfo;
	private String shippingInfo;
	private Date ctime;

	public TStateInfo() {
	}

	public TStateInfo(String stateCode, String currencyCode, String cardInfo,
			String shippingInfo, Date ctime) {
		this.stateCode = stateCode;
		this.currencyCode = currencyCode;
		this.cardInfo = cardInfo;
		this.shippingInfo = shippingInfo;
		this.ctime = ctime;
	}

	public String getStateCode() {
		return this.stateCode;
	}

	public void setStateCode(String stateCode) {
		this.stateCode = stateCode;
	}

	public String getCurrencyCode() {
		return this.currencyCode;
	}

	public void setCurrencyCode(String currencyCode) {
		this.currencyCode = currencyCode;
	}

	public String getCardInfo() {
		return this.cardInfo;
	}

	public void setCardInfo(String cardInfo) {
		this.cardInfo = cardInfo;
	}

	public String getShippingInfo() {
		return this.shippingInfo;
	}

	public void setShippingInfo(String shippingInfo) {
		this.shippingInfo = shippingInfo;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

}
