package com.qpp.model;

// Generated Sep 24, 2014 2:42:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TStoreOrder generated by hbm2java
 */
public class TStoreOrder implements java.io.Serializable {

	private long id;
	private long storeId;
	private String comment;
	private Date ctime;
	private int amount;
	private long byuserId;
	private String status;

	public TStoreOrder() {
	}

	public TStoreOrder(Date ctime, int amount, String status) {
		this.ctime = ctime;
		this.amount = amount;
		this.status = status;
	}

	public TStoreOrder(long storeId, String comment, Date ctime, int amount,
			long byuserId, String status) {
		this.storeId = storeId;
		this.comment = comment;
		this.ctime = ctime;
		this.amount = amount;
		this.byuserId = byuserId;
		this.status = status;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getStoreId() {
		return this.storeId;
	}

	public void setStoreId(long storeId) {
		this.storeId = storeId;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public long getByuserId() {
		return this.byuserId;
	}

	public void setByuserId(long byuserId) {
		this.byuserId = byuserId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
