package com.qpp.model;

// Generated Sep 24, 2014 2:42:53 PM by Hibernate Tools 3.4.0.CR1

/**
 * TStore generated by hbm2java
 */
public class TStore implements java.io.Serializable {

	private long userId;
	private String name;
	private String comment;
	private String seo;
	private String state;
	private String contacts;
	private int phone;
	private String template;
	private String popularize;
	private String share;
	private String gameType;

	public TStore() {
	}

	public TStore(String name, String state, int phone, String template) {
		this.name = name;
		this.state = state;
		this.phone = phone;
		this.template = template;
	}

	public TStore(String name, String comment, String seo, String state,
			String contacts, int phone, String template, String popularize,
			String share, String gameType) {
		this.name = name;
		this.comment = comment;
		this.seo = seo;
		this.state = state;
		this.contacts = contacts;
		this.phone = phone;
		this.template = template;
		this.popularize = popularize;
		this.share = share;
		this.gameType = gameType;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getSeo() {
		return this.seo;
	}

	public void setSeo(String seo) {
		this.seo = seo;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getContacts() {
		return this.contacts;
	}

	public void setContacts(String contacts) {
		this.contacts = contacts;
	}

	public int getPhone() {
		return this.phone;
	}

	public void setPhone(int phone) {
		this.phone = phone;
	}

	public String getTemplate() {
		return this.template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}

	public String getPopularize() {
		return this.popularize;
	}

	public void setPopularize(String popularize) {
		this.popularize = popularize;
	}

	public String getShare() {
		return this.share;
	}

	public void setShare(String share) {
		this.share = share;
	}

	public String getGameType() {
		return this.gameType;
	}

	public void setGameType(String gameType) {
		this.gameType = gameType;
	}

}
