package com.qpp.model;

// Generated Aug 12, 2014 11:53:34 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TStoreOrder generated by hbm2java
 */
public class TStoreOrder implements java.io.Serializable {

	private String id;
	private TUser TUser;
	private TStore TStore;
	private String comment;
	private Date ctime;
	private int amount;
	private String status;

	public TStoreOrder() {
	}

	public TStoreOrder(String id, TUser TUser, String comment, Date ctime,
			int amount, String status) {
		this.id = id;
		this.TUser = TUser;
		this.comment = comment;
		this.ctime = ctime;
		this.amount = amount;
		this.status = status;
	}

	public TStoreOrder(String id, TUser TUser, TStore TStore, String comment,
			Date ctime, int amount, String status) {
		this.id = id;
		this.TUser = TUser;
		this.TStore = TStore;
		this.comment = comment;
		this.ctime = ctime;
		this.amount = amount;
		this.status = status;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	public TStore getTStore() {
		return this.TStore;
	}

	public void setTStore(TStore TStore) {
		this.TStore = TStore;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
