package com.qpp.model;

// Generated Aug 28, 2014 4:18:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TStoreOrder generated by hbm2java
 */
public class TStoreOrder implements java.io.Serializable {

	private int id;
	private TStore storeId;
	private String comment;
	private Date ctime;
	private int amount;
	private int byuserId;
	private String status;

	public TStoreOrder() {
	}

	public TStoreOrder(Date ctime, int amount, String status) {
		this.ctime = ctime;
		this.amount = amount;
		this.status = status;
	}

	public TStoreOrder(TStore storeId, String comment, Date ctime, int amount,
			int byuserId, String status) {
        this.storeId=storeId;
		this.comment = comment;
		this.ctime = ctime;
		this.amount = amount;
		this.byuserId = byuserId;
		this.status = status;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

    public TStore getStoreId() {
        return storeId;
    }

    public void setStoreId(TStore storeId) {
        this.storeId = storeId;
    }

    public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public int getByuserId() {
		return this.byuserId;
	}

	public void setByuserId(int byuserId) {
		this.byuserId = byuserId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
