package com.qpp.model;

// Generated Aug 12, 2014 11:53:34 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TUserOrder generated by hbm2java
 */
public class TUserOrder implements java.io.Serializable {

	private String id;
	private TUser TUser;
	private String type;
	private int amount;
	private Date ctime;
	private String comment;
	private char payType;
	private String status;

	public TUserOrder() {
	}

	public TUserOrder(String id, TUser TUser, String type, int amount,
			Date ctime, String comment, char payType, String status) {
		this.id = id;
		this.TUser = TUser;
		this.type = type;
		this.amount = amount;
		this.ctime = ctime;
		this.comment = comment;
		this.payType = payType;
		this.status = status;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public char getPayType() {
		return this.payType;
	}

	public void setPayType(char payType) {
		this.payType = payType;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
