package com.qpp.model;

// Generated Sep 24, 2014 2:42:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TUserOrder generated by hbm2java
 */
public class TUserOrder implements java.io.Serializable {

	private long id;
	private long userId;
	private String type;
	private double amount;
	private Date ctime;
	private String comment;
	private Character payType;
	private String status;

	public TUserOrder() {
	}

	public TUserOrder(double amount, Date ctime, String status) {
		this.amount = amount;
		this.ctime = ctime;
		this.status = status;
	}

	public TUserOrder(long userId, String type, double amount, Date ctime,
			String comment, Character payType, String status) {
		this.userId = userId;
		this.type = type;
		this.amount = amount;
		this.ctime = ctime;
		this.comment = comment;
		this.payType = payType;
		this.status = status;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Character getPayType() {
		return this.payType;
	}

	public void setPayType(Character payType) {
		this.payType = payType;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
