package com.qpp.model;

// Generated Aug 12, 2014 11:53:34 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TUser generated by hbm2java
 */
public class TUser implements java.io.Serializable {

	private String id;
	private TGift TGift;
	private String name;
	private Date birthDay;
	private int phone;
	private String address;
	private String province;
	private String city;
	private String area;
	private String email;
	private String type;
	private String password;
	private String nickname;
	private double money;
	private int score;
	private String sex;
	private String comment;
	private char status;
	private String voucher;
	private Date ctime;
	private Date utime;
	private String countryCode;
	private Set<TConvert> TConverts = new HashSet<TConvert>(0);
	private TStore TStore;
	private Set<TStoreOrder> TStoreOrders = new HashSet<TStoreOrder>(0);
	private Set<TUserOrder> TUserOrders = new HashSet<TUserOrder>(0);
//	private Set<TScore> TScores = new HashSet<TScore>(0);
	private TFavorite TFavorite;
	private Set<TCartItem> TCartItems = new HashSet<TCartItem>(0);
	private Set<TOrder> TOrders = new HashSet<TOrder>(0);
	private Set<TComment> TComments = new HashSet<TComment>(0);

	public TUser() {
	}

	public TUser(String id, String name, int phone, String address,
			String province, String city, String area, String email,
			String type, String nickname, double money, String sex,
			String comment, char status, String voucher, Date ctime,
			Date utime, String countryCode) {
		this.id = id;
		this.name = name;
		this.phone = phone;
		this.address = address;
		this.province = province;
		this.city = city;
		this.area = area;
		this.email = email;
		this.type = type;
		this.nickname = nickname;
		this.money = money;
		this.sex = sex;
		this.comment = comment;
		this.status = status;
		this.voucher = voucher;
		this.ctime = ctime;
		this.utime = utime;
		this.countryCode = countryCode;
	}

	public TUser(String id, TGift TGift, String name, Date birthDay, int phone,
			String address, String province, String city, String area,
			String email, String type, String password, String nickname,
			double money, int score, String sex, String comment,
			char status, String voucher, Date ctime, Date utime,
			String countryCode, Set<TConvert> TConverts, TStore TStore,
			Set<TStoreOrder> TStoreOrders, Set<TUserOrder> TUserOrders,
			TFavorite TFavorite,
			Set<TCartItem> TCartItems, Set<TOrder> TOrders,
			Set<TComment> TComments) {
		this.id = id;
		this.TGift = TGift;
		this.name = name;
		this.birthDay = birthDay;
		this.phone = phone;
		this.address = address;
		this.province = province;
		this.city = city;
		this.area = area;
		this.email = email;
		this.type = type;
		this.password = password;
		this.nickname = nickname;
		this.money = money;
		this.score = score;
		this.sex = sex;
		this.comment = comment;
		this.status = status;
		this.voucher = voucher;
		this.ctime = ctime;
		this.utime = utime;
		this.countryCode = countryCode;
		this.TConverts = TConverts;
		this.TStore = TStore;
		this.TStoreOrders = TStoreOrders;
		this.TUserOrders = TUserOrders;
//		this.TScores = TScores;
		this.TFavorite = TFavorite;
		this.TCartItems = TCartItems;
		this.TOrders = TOrders;
		this.TComments = TComments;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public TGift getTGift() {
		return this.TGift;
	}

	public void setTGift(TGift TGift) {
		this.TGift = TGift;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getBirthDay() {
		return this.birthDay;
	}

	public void setBirthDay(Date birthDay) {
		this.birthDay = birthDay;
	}

	public int getPhone() {
		return this.phone;
	}

	public void setPhone(int phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public double getMoney() {
		return this.money;
	}

	public void setMoney(double money) {
		this.money = money;
	}

	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	public String getVoucher() {
		return this.voucher;
	}

	public void setVoucher(String voucher) {
		this.voucher = voucher;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public Date getUtime() {
		return this.utime;
	}

	public void setUtime(Date utime) {
		this.utime = utime;
	}

	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	public Set<TConvert> getTConverts() {
		return this.TConverts;
	}

	public void setTConverts(Set<TConvert> TConverts) {
		this.TConverts = TConverts;
	}

	public TStore getTStore() {
		return this.TStore;
	}

	public void setTStore(TStore TStore) {
		this.TStore = TStore;
	}

	public Set<TStoreOrder> getTStoreOrders() {
		return this.TStoreOrders;
	}

	public void setTStoreOrders(Set<TStoreOrder> TStoreOrders) {
		this.TStoreOrders = TStoreOrders;
	}

	public Set<TUserOrder> getTUserOrders() {
		return this.TUserOrders;
	}

	public void setTUserOrders(Set<TUserOrder> TUserOrders) {
		this.TUserOrders = TUserOrders;
	}
//
//	public Set<TScore> getTScores() {
//		return this.TScores;
//	}
//
//	public void setTScores(Set<TScore> TScores) {
//		this.TScores = TScores;
//	}

	public TFavorite getTFavorite() {
		return this.TFavorite;
	}

	public void setTFavorite(TFavorite TFavorite) {
		this.TFavorite = TFavorite;
	}

	public Set<TCartItem> getTCartItems() {
		return this.TCartItems;
	}

	public void setTCartItems(Set<TCartItem> TCartItems) {
		this.TCartItems = TCartItems;
	}

	public Set<TOrder> getTOrders() {
		return this.TOrders;
	}

	public void setTOrders(Set<TOrder> TOrders) {
		this.TOrders = TOrders;
	}

	public Set<TComment> getTComments() {
		return this.TComments;
	}

	public void setTComments(Set<TComment> TComments) {
		this.TComments = TComments;
	}

}
