package com.qpp.model;

// Generated Aug 28, 2014 4:18:51 PM by Hibernate Tools 3.4.0.CR1

/**
 * TUserEmail generated by hbm2java
 */
public class TUserEmail implements java.io.Serializable {

	private int id;
	private TUser userId;
	private TMailPublish emailId;

	public TUserEmail() {
	}

	public TUserEmail(TUser userId, TMailPublish emailId) {
        this.userId=userId;
        this.emailId=emailId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

    public TUser getUserId() {
        return userId;
    }

    public void setUserId(TUser userId) {
        this.userId = userId;
    }

    public TMailPublish getEmailId() {
        return emailId;
    }

    public void setEmailId(TMailPublish emailId) {
        this.emailId = emailId;
    }
}
