package com.qpp.model;

// Generated Sep 24, 2014 2:42:53 PM by Hibernate Tools 3.4.0.CR1

/**
 * TUserEmail generated by hbm2java
 */
public class TUserEmail implements java.io.Serializable {

	private long id;
	private long userId;
	private long emailId;

	public TUserEmail() {
	}

	public TUserEmail(long userId, long emailId) {
		this.userId = userId;
		this.emailId = emailId;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public long getEmailId() {
		return this.emailId;
	}

	public void setEmailId(long emailId) {
		this.emailId = emailId;
	}

}
