package com.qpp.model;

// Generated Aug 28, 2014 4:18:51 PM by Hibernate Tools 3.4.0.CR1

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TUser generated by hbm2java
 */
public class TUser implements java.io.Serializable {

	private int id;
	private TGift present;
	private String name;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date birthDay;
	private String phone;
	private String address;
	private String province;
	private String city;
	private String area;
	private String email;
	private String type;
	private String password;
	private String nickname;
	private Double money;
	private int score;
	private String sex;
	private String comment;
	private String status;
	private String voucher;
	private Date ctime;
	private Date utime;
	private String countryCode;
	private String roles;
	private TStore TStore;
	private Set<TUserOrder> TUserOrders = new HashSet<TUserOrder>(0);
	private Set<TUserEmail> TUserEmails = new HashSet<TUserEmail>(0);
	private Set<TScore> TScores = new HashSet<TScore>(0);
	private TFavorite TFavorite;
	private Set<TCartItem> TCartItems = new HashSet<TCartItem>(0);
	private Set<TConvert> TConverts = new HashSet<TConvert>(0);
	private Set<TComment> TComments = new HashSet<TComment>(0);

	public TUser() {
	}

	public TUser(String name, String city, String email, String type,
			String password, String sex, Date ctime, Date utime,
			String countryCode) {
		this.name = name;
		this.city = city;
		this.email = email;
		this.type = type;
		this.password = password;
		this.sex = sex;
		this.ctime = ctime;
		this.utime = utime;
		this.countryCode = countryCode;
	}

	public TUser(TGift present, String name, Date birthDay, String phone,
			String address, String province, String city, String area,
			String email, String type, String password, String nickname,
			Double money, int score, String sex, String comment,
			String status, String voucher, Date ctime, Date utime,
			String countryCode, String roles, TStore TStore,
			Set<TUserOrder> TUserOrders, Set<TUserEmail> TUserEmails,
			Set<TScore> TScores, TFavorite TFavorite,
			Set<TCartItem> TCartItems, Set<TConvert> TConverts,
			Set<TComment> TComments) {
        this.present=present;
		this.name = name;
		this.birthDay = birthDay;
		this.phone = phone;
		this.address = address;
		this.province = province;
		this.city = city;
		this.area = area;
		this.email = email;
		this.type = type;
		this.password = password;
		this.nickname = nickname;
		this.money = money;
		this.score = score;
		this.sex = sex;
		this.comment = comment;
		this.status = status;
		this.voucher = voucher;
		this.ctime = ctime;
		this.utime = utime;
		this.countryCode = countryCode;
		this.roles = roles;
		this.TStore = TStore;
		this.TUserOrders = TUserOrders;
		this.TUserEmails = TUserEmails;
		this.TScores = TScores;
		this.TFavorite = TFavorite;
		this.TCartItems = TCartItems;
		this.TConverts = TConverts;
		this.TComments = TComments;
	}

    public TGift getPresent() {
        return present;
    }

    public void setPresent(TGift present) {
        this.present = present;
    }

    public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getBirthDay() {
		return this.birthDay;
	}

	public void setBirthDay(Date birthDay) {
		this.birthDay = birthDay;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public Double getMoney() {
		return this.money;
	}

	public void setMoney(Double money) {
		this.money = money;
	}

	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getVoucher() {
		return this.voucher;
	}

	public void setVoucher(String voucher) {
		this.voucher = voucher;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public Date getUtime() {
		return this.utime;
	}

	public void setUtime(Date utime) {
		this.utime = utime;
	}

	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	public String getRoles() {
		return this.roles;
	}

	public void setRoles(String roles) {
		this.roles = roles;
	}

	public TStore getTStore() {
		return this.TStore;
	}

	public void setTStore(TStore TStore) {
		this.TStore = TStore;
	}

	public Set<TUserOrder> getTUserOrders() {
		return this.TUserOrders;
	}

	public void setTUserOrders(Set<TUserOrder> TUserOrders) {
		this.TUserOrders = TUserOrders;
	}

	public Set<TUserEmail> getTUserEmails() {
		return this.TUserEmails;
	}

	public void setTUserEmails(Set<TUserEmail> TUserEmails) {
		this.TUserEmails = TUserEmails;
	}

	public Set<TScore> getTScores() {
		return this.TScores;
	}

	public void setTScores(Set<TScore> TScores) {
		this.TScores = TScores;
	}

	public TFavorite getTFavorite() {
		return this.TFavorite;
	}

	public void setTFavorite(TFavorite TFavorite) {
		this.TFavorite = TFavorite;
	}

	public Set<TCartItem> getTCartItems() {
		return this.TCartItems;
	}

	public void setTCartItems(Set<TCartItem> TCartItems) {
		this.TCartItems = TCartItems;
	}

	public Set<TConvert> getTConverts() {
		return this.TConverts;
	}

	public void setTConverts(Set<TConvert> TConverts) {
		this.TConverts = TConverts;
	}

	public Set<TComment> getTComments() {
		return this.TComments;
	}

	public void setTComments(Set<TComment> TComments) {
		this.TComments = TComments;
	}

}
