package com.qpp.model;

// Generated Sep 24, 2014 2:42:53 PM by Hibernate Tools 3.4.0.CR1

import com.qpp.validate.KeyInTable;

import javax.validation.constraints.NotNull;

/**
 * TUserRole generated by hbm2java
 */
public class TUserRole implements java.io.Serializable {

	private long oid;
    @NotNull
    @KeyInTable(value = TUser.class)
	private long userId;
    @NotNull
    @KeyInTable(value = TRole.class)
	private long roleId;

	public TUserRole() {
	}

	public TUserRole(int userId, int roleId) {
		this.userId = userId;
		this.roleId = roleId;
	}

	public long getOid() {
		return this.oid;
	}

	public void setOid(long oid) {
		this.oid = oid;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        TUserRole userRole = (TUserRole) o;

        if (userId != userRole.userId) return false;
        if (roleId != userRole.roleId) return false;

        return true;
    }

    @Override
    public int hashCode() {
        long result = userId;
        result = 31 * result + roleId;
        return Integer.parseInt(String.valueOf(result));
    }

}
